### ISSUE TITLE
Deprecated function

### ISSUE THREAD

**Issue by ilicmarko** [Miki96/miki96.github.io#1]
https://github.com/Miki96/miki96.github.io/blob/1d3b84ed4127ca5cf58179e6aec978365df745dd/js/models.js#L427

`getPosition` is deprecated and should be replaced with 

```js
position.getPositionFromMatrix( planets[i].mesh.matrixWorld );
```
Great project!

**Comment by Miki96** [comment]
Deprecated function fixed. Thank you.
